spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Y1012jqkhkp
    url: jdbc:mysql://localhost:3306/jrtp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081